[package]
name = "atomic-bomb-engine-py"
version = "0.2.4"
edition = "2021"

[lib]
name = "atomic_bomb_engine"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic-bomb-engine = "0.2.2"
pyo3 = "0.20.3"
tokio = "1.36.0"
pyo3-asyncio = { version = "0.20.0", features = ["tokio-runtime"] }
