name: Build Python Wheels on Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows_amd64
    steps:
      - name: 签出代码
        uses: actions/checkout@v3

      - name: 构建python包
        run: |
          C:\Users\Administrator\rust-build\Scripts\maturin.exe build --release --interpreter python3.8 --interpreter python3.9 --interpreter python3.10 --interpreter python3.11 --interpreter python3.12

