name: Build Python Wheels on Linux
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: linux_amd64

    env:
      http_proxy: http://10.0.0.54:1080
      https_proxy: http://10.0.0.54:1080
      all_proxy: socks5://10.0.0.54:1080

    steps:
      - name: 签出代码
        uses: actions/checkout@v3

      - name: 设置cargo环境变量
        run: echo "PATH=$PATH:/home/qyzhg/.cargo/bin" >> $GITHUB_ENV

      - name: 构建python包
        run: /home/qyzhg/python-envs/python3.12/bin/maturin build --release --target x86_64-apple-darwin

      - name: 上传构建的whl包到PyPI
        run: |
          /home/qyzhg/python-envs/python3.12/bin/twine upload --repository pypi --config-file /home/qyzhg/.pypirc ./target/wheels/*
