name: Build macOS Python Wheels on Linux

on:
  push:
    branches:
      - master

jobs:
  build-wheels:
    runs-on: linux_amd64

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: 签出代码
        uses: actions/checkout@v3

      - name: 安装 Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
          override: true

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel
          pip install maturin

      - name: 构建wheels
        run: |
          maturin build --release -i python3.8 -i python3.9 -i python3.10 -i python3.11 -i python3.12
