name: Build Python Wheels on Linux
on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: linux_amd64

    env:
      http_proxy: http://10.0.0.54:1080
      https_proxy: http://10.0.0.54:1080
      all_proxy: socks5://10.0.0.54:1080

    steps:
      - name: 签出代码
        uses: actions/checkout@v3

      - name: 设置cargo环境变量
        run: echo "PATH=$PATH:/home/qyzhg/.cargo/bin" >> $GITHUB_ENV

      - name: 构建python包
        run: /home/qyzhg/maturin-builder/bin/maturin build --release -i python3.8 -i python3.9 -i python3.10 -i python3.11 -i python3.12

      - name: 上传构建的whl包到PyPI
        run: |
          /home/qyzhg/maturin-builder/bin/twine upload --repository pypi --config-file /home/qyzhg/.pypirc ./target/wheels/*
