name: Build Python Wheels on Windows
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: win_amd64
#    Start-Process -FilePath "C:\Users\Administrator\act_runner.exe" -ArgumentList "daemon -c C:\Users\Administrator\.runner"

    env:
      http_proxy: http://10.0.0.54:1080
      https_proxy: http://10.0.0.54:1080
      all_proxy: socks5://10.0.0.54:1080

    steps:
      - name: 签出代码
        uses: actions/checkout@v3
      - name: 构建python包
        run: |
          cargo --version
          C:\Users\Administrator\rust-build\Scripts\maturin.exe build --release --interpreter python3.8 --interpreter python3.9 --interpreter python3.10 --interpreter python3.11 --interpreter python3.12
        env:
          PYTHONIOENCODING: utf-8
      - name: 上传构建的whl包到PyPI
        run: |
          C:\Users\Administrator\rust-build\Scripts\twine.exe upload --repository pypi --config-file C:\Users\Administrator\.pypirc .\target\wheels\*
        env:
          PYTHONIOENCODING: utf-8